AWSTemplateFormatVersion: 2010-09-09

Description: test

Parameters:
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
    ConstraintDescription: must be a list of at least two existing subnets associated with at least two different availability zones. They should be residing in the selected Virtual Private Cloud.

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.

  ClusterName:
    Type: String

  TaskDefinitionFamilyName:
    Type: String

  DockerImage:
    Type: String

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName


  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskDefinitionFamilyName
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc #needed for Fargate
      ContainerDefinitions:
        - Name: !Ref TaskDefinitionFamilyName
          Image: !Ref DockerImage
          PortMappings:
            - ContainerPort: 80
      RequiresCompatibilities:
        - EC2
        - FARGATE

  # ServiceLoadBalancer:
  #   Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  #   Properties:
  #     Subnets: !Ref Subnets

  # ALBListener:
  #   Type: AWS::ElasticLoadBalancingV2::Listener
  #   Properties:
  #     DefaultActions:
  #       - Type: forward
  #         TargetGroupArn: !Ref ALBTargetGroup
  #     LoadBalancerArn: !Ref ServiceLoadBalancer
  #     Port: 80
  #     Protocol: HTTP

  # ALBTargetGroup:
  #   Type: AWS::ElasticLoadBalancingV2::TargetGroup
  #   Properties:
  #     Port: 80
  #     Protocol: HTTP
  #     VpcId: !Ref VpcId

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Join [ "", [!Ref TaskDefinitionFamilyName  ,Serv ] ]
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref Subnets

