on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      IMAGE:
        required: true
        type: string
      ECS_CLUSTER:
        required: true
        type: string
      ECS_SERVICE:
        required: true
        type: string
      TASK_DEFINITION:
        required: true
        type: string
      CONTAINER_NAME:
        required: true
        type: string
      ENV_VARIABLES:
        required: false
        type: string

    secrets:
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy storybook
    steps:
      - run: echo ${{inputs.IMAGE}}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Fill in the new image ID in the Amazon ECS task definition for storybook
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ inputs.TASK_DEFINITION }}
          container-name: ${{ inputs.CONTAINER_NAME }}
          image: ${{ inputs.IMAGE}}

      - run: |
          echo ${{ steps.task-def.outputs.task-definition }}

      - id: replace-task-env
        uses: buildman-project/gh-action-modify-aws-task@main
        with:
          task-definition-content: ${{ steps.task-def.outputs.task-definition }}
          env-variables: ${{ inputs.ENV_VARIABLES }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.replace-task-env.outputs.final-task-def}}
          service: ${{ inputs.ECS_SERVICE }}
          cluster: ${{ inputs.ECS_CLUSTER }}
          wait-for-service-stability: true
