on:
  workflow_call:
    inputs:
      ECR_REPOSITORY:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
      DOCKERFILE_NAME:
        required: false
        default: Dockerfile
        type: string
      BUILD_ARGS:
        required: false
        default: ""
        type: string

    secrets:
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      BUILD_ARGS:
        required: false

    outputs:
      image:
        value: ${{ jobs.build-and-upload-image.outputs.image }}

jobs:
  build-and-upload-image:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
          mask-aws-account-id: "no"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: generate docker build script
        id: generate-build-script
        uses: buildman-project/gh-action-generate-build-script@main
        with:
          Tag: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ECR_REPOSITORY }}:${{ inputs.IMAGE_TAG }}
          ParamsEnv: ${{ inputs.BUILD_ARGS }}
          DockerfileName: ${{ inputs.DOCKERFILE_NAME }}
        env:
          BUILD_ARGS: ${{ secrets.BUILD_ARGS }}

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          ${{ steps.generate-build-script.outputs.script }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
