name: deploy base infrastructure

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
        description: aws region
        default: us-east-1

    secrets:
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true

    permissions:
      id-token: write
      contents: read

jobs:
  test_workflow:
    name: shell command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
          mask-aws-account-id: "no"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: create-server-resources
        run: |
          aws cloudformation create-stack --stack-name buildman-dev --template-body file://project-base-cf.yml --parameters file://project-params.json --capabilities CAPABILITY_NAMED_IAM
          aws cloudformation wait stack-create-complete --stack-name buildman-dev
