name: get global variables

on:
  workflow_call:
    outputs:
      LOAD_BALANCER_URL:
        value: ${{ jobs.get-aws-data.outputs.LOAD_BALANCER_URL }}

jobs:
  get-aws-data:
    runs-on: ubuntu-latest
    outputs:
      LOAD_BALANCER_URL: ${{ steps.get-aws-data.outputs.LOAD_BALANCER_URL }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - id: get-aws-data
        uses: buildman-project/gh-action-get-stack-output@main
        with:
          StackName: ${{ vars.AWS_BASE_STACK_NAME }}
          Outputs: LoadBalancerUrl

      - name: echo-data
        run: |
          echo "load balancer url = ${{ steps.get-aws-data.outputs.LOAD_BALANCER_URL }}"
