name: get global variables

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test_workflow:
    name: shell command
    runs-on: ubuntu-latest
    outputs:
      GENERAL_ENV: ${{ steps.get-global-vars.outputs.GENERAL_ENV }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: buildman-project/base-infrastructure-deploy

      - id: get-global-vars
        run: |
          echo "GENERAL_ENV=$(cat general_env_variables.env)" >> $GITHUB_OUTPUT

      - id: general-env-outputs
        run: |
          echo ${{ steps.get-global-vars.outputs.GENERAL_ENV }}
