name: test

on: workflow_dispatch

jobs:
  test_workflow:
    name: shell command
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: test script
        run: .github/cli_commands/test.sh
